"""make user phone nullable

Revision ID: d006ce48fb8a
Revises: fdc5b834c32f
Create Date: 2026-07-28 04:11:15.355401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text, String, Integer, Boolean, Float
from sqlalchemy.dialects import postgresql
import app.common.db_types


revision: str = 'd006ce48fb8a'
down_revision: Union[str, None] = 'fdc5b834c32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('phone', existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('phone', existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###
